### PR TITLE
feat: Add Dark Mode

### PR DESCRIPTION
**Pull request by Itezaz-ul-Hassan**
Dark mode has been implemented

### CODE REVIEW

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Please review the code. Dark mode is implemented as discussed in this [issue](https://github.com/KriteshTimsina/Wassupbroo-Chat-App/issues/1)

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Also can you add `hacktoberfest` and `hacktoberfest-accepted` labels in PR

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Ok so here's one issue:
Try removing theme from local storage and change the dark mode toggle. It doesn't work the first time. Try changing switch to light mode Icon when it's darkmode and vice versa. This might solve your issue.

**Comment by KriteshTimsina** [comment]
Sure work on it.

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Can you add `hacktoberfest` and `hacktoberfest-accepted` labels on this PR. Thanks

**Comment by KriteshTimsina** [comment]
Done!

**Pull request merged**
