### PR TITLE
fix: Dark mode icons

### PR DESCRIPTION
**Pull request by Itezaz-ul-Hassan**
This PR fixes the behaviour of theme and the icons. It also has many UI improvements when in dark mode

### CODE REVIEW

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina This PR fixes this [issue](https://github.com/KriteshTimsina/Wassupbroo-Chat-App/issues/8)

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Can you add `hacktoberfest` and `hacktoberfest-accepted` labels on this PR

**Comment by KriteshTimsina** [comment]
GG! THANK YOU FOR YOUR CONTRIBUTION

**Review by KriteshTimsina — COMMENTED** [review]
Looks good

**Pull request merged**
